### ISSUE TITLE
Dependency Conflicts

### ISSUE THREAD

**Issue by Nemesis9765** [simplesamlphp/xmlseclibs#4] opened 2015-09-18 21:09 UTC
Since the latest tag of simplesamlphp uses this library, it conflicts w/ other composer based libraries that use this library.  I noticed that currently master fixes this, but there's no tag which incorporates the change, so until that happens, I'd suggest wrapping the entire library in an if statement,

```
<?php

if (!class_exists('XMLSecurityKey')) {
      ....
}
```

**Comment by jaimeperez** [comment] 2015-09-21 11:27
Hi @Nemesis9765!

This repo was intended as a read-only mirror of the upstream repo, except for a fix that was creating huge performance issues in SimpleSAMLphp. Now that the fix has been incorporated upstream and *xmlseclibs* is in github, we stopped using this repo and went back to the original.

There will be a new release soon solving this issue. Meanwhile, the recommended way to install SimpleSAMLphp is by downloading the latest stable release, not with composer (not yet). Those using composer to install it are on their own right now, unfortunately.

**Closed by jaimeperez** 2015-09-21 11:27 UTC
